### PR TITLE
Topic/spring boot

### PR DESCRIPTION
**Pull request by jnizet**
Rewrite the application with Spring-Boot, and change a few things:
- The REST services are under localhost:8080/api instead of loclhost:8080/poneyserver
- Use the latest Spring Boot, and thus the latest spring as well. Had to change a few things regarding web sockets to disable same-origin policy introduced in recent Spring
- Use latest Swagger 2
- The database now contains 25 races instead of 5, and 5 of them are already finished, allowing to test the filter directly

Advantages of this version over the previous one:
- I've learnt things
- The size of the app is smaller
- We're more up-to-date
- The URLs are cleaner and simpler
- The errors, handled by Spring, are cleaner
- Exceptions will now appear in the console rather than in log files

### CODE REVIEW

**Comment by jnizet** [comment]
Note that I have a branch ready to be pushed in the Formation project, containing the updated poneyserver binaries, and the updated slides and poneyracer instructions. Since it's quite heavy, I'll wait for this PR to be merged before submitting the other one. It would be nice if I could test that on the next training, next Wednesday.

**Comment by cexbrayat** [comment]
Cool, that was on my TODO list :+1: 

I'm reviewing it : I was wondering if you gave a shot to https://github.com/spring-projects/spring-restdocs for the docs instead of Swagger ? I never tried, so I don't know what it's worth...

**Comment by cexbrayat** [comment]
It works great! Just had to change the api endpoint.

I updated the soluce https://bitbucket.org/ninjasquad/poneyracer/commits/all

You can merge when you have seen my comments.

**Comment by jnizet** [comment]
I didn't test spring-restdocs. Might be cool to test it, bu I feel Swagger is simple and sufficient for this app. I also find it cool as a test to show that everything works fine.

**Pull request merged**
